project:
  type: website

website:
  title: "Time Series Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: Introduction
      - href: data-sources.qmd
        text: Data Sources
      - href: data-visualisation.qmd
        text: Data Visualisation
      - href: exploratory-data-analysis.qmd
        text: Exploratory Data Analysis
      - href: arma-arima-sarima-models.qmd
        text: ARMA, ARIMA, SARIMA Models
      - href: arimax-sarimax-var.qmd
        text: ARIMAX, SARIMAX, VAR Models
      - href: financial-time-series-models(arch-garch).qmd
        text: Financial Time Series Models (ARCH, GARCH)
      - href: deep-learning-for-TS.qmd
        text: Deep Learning for Time Series
      - href: conclusion.qmd
        text: Conclusion


format:
  html:
    theme: cerulean
    css: styles.css
    toc: true